src/library/urls.py
from django.urls import path

from . import views

app_name = 'library'
urlpatterns = [
  path('', views.index, name='index'),
  path('<int:pk>/', views.BookDetailView.as_view(), name='bookDetail'),
  path('author/<int:author_id>/', views.authorDetail, name='authorDetail'),
  path('genre/<int:genre_id>', views.genreDetail,name='genreDetail'),
  path('new-book-form/', views.newBookForm, name='newBookForm'),
  path('process-new-book', views.processNewBook, name='processNewBook'),
]

src/src/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('library/', include('library.urls')),
    path('admin/', admin.site.urls),
]

src/library/models.py
from turtle import title
from django.db import models

# Create your models here.
from django.db import models

class Author(models.Model):
  firstName = models.CharField(max_length=250, blank=True)
  lastName = models.CharField(max_length=250, blank=True)

  def __str__(self):
    self.firstName + self.lastName
    return self.firstName + ' ' + self.lastName

class Genre(models.Model):
  name = models.CharField(max_length=250, blank=True)

  def __str__(self):
    return self.name

class Book(models.Model):
  title = models.CharField(max_length=250)
  author = models.ForeignKey(Author, on_delete=models.RESTRICT)
  genre = models.ForeignKey(Genre, on_delete=models.RESTRICT)

  def __str__(self):
    return self.title

src/library/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic


from .models import Book, Author, Genre


# Create your views here.
def index(request):
  books = Book.objects.order_by('title')
  context = {
    'books':books,
  }

  return render(request, 'library/index.html', context)

class BookDetailView(generic.DetailView):
  model = Book
  template_name = 'library/book-detail.html'

def authorDetail(request, author_id):
  author = get_object_or_404(Author, pk=author_id)
  books = Book.objects.filter(author_id=author_id)
  return render(request, 'library/author-detail.html', {"author":author, "books":books})

def genreDetail(request, genre_id):
  genre = get_object_or_404(Genre, pk=genre_id)
  books = Book.objects.filter(genre_id=genre_id)
  return render(request, 'library/genre-detail.html', {"genre":genre, "books":books})

def newBookForm(request):
  authors = Author.objects.all()
  genres = Genre.objects.all()

  return render(request, 'library/new-book-form.html', {'authors':authors, 'genres':genres})

def processNewBook(request):
  title = request.POST['title']
  author_id = request.POST['author']
  genre_id = request.POST['genre']

  if title and author_id and genre_id:
    author = get_object_or_404(Author, pk=author_id)
    genre = get_object_or_404(Genre, pk=genre_id)
    book = Book(title=title, author=author, genre=genre)
    book.save()
    return HttpResponseRedirect(reverse('library:bookDetail', args=(book.pk,)))
  else:
    authors = Author.objects.all()
    genres = Genre.objects.all()
    return render(request, 'library/new-book-form.html', {'authors':authors, 'genres':genres, 'error_message': "Improper Book Data"})  

  

src/library/templates/library/author-detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{%static 'library/style.css' %}">

<h1>{{author.firstName|add:' '|add:author.lastName}}</h1>
<ul>
{%for book in books%}
  <li><a href="{% url 'library:bookDetail' book.id%}">{{ book.title }}</a></li>
{%endfor%}
</ul>

src/library/templates/library/book-detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{%static 'library/style.css' %}">  

<h1>{{book}}</h1>
<p><a href="{% url 'library:authorDetail' book.author.id%}">{{book.author}}</a></p>
<p><a href="{% url 'library:genreDetail' book.genre.id%}">{{book.genre}}</a></p>

src/library/templates/library/genre-detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{%static 'library/style.css' %}">

<h1>{{genre.name}}</h1>
<ul>
  {%for book in books%}
  <li><a href="{% url 'library:bookDetail' book.id%}">{{ book.title }}</a></li>
  {%endfor%}
</ul>

src/library/templates/library/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{%static 'library/style.css' %}">

{% if books %}
<ul>
  {% for book in books %}
  <li><a href="{% url 'library:bookDetail' book.id%}">{{ book.title }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No books in library</p>
{% endif %}
<p><a href="{% url 'library:newBookForm'%}">Add a book</a></p>

src/library/templates/library/new-book-form.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{%static 'library/style.css' %}">

<form action="{% url 'library:processNewBook' %}" method="post">
  {% csrf_token %}
  <fieldset>
    <legend>
      <h1>Add a new book</h1>
    </legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
      <label for="title">Title:</label>
      <input type='text' name="title"></input>

      <label for='author'>Choose an Author:</label>
      <select id='author' name="author">
        {% for author in authors %}
            <option value="{{author.pk}}">{{author.firstName|add:' '|add:author.lastName}}</option>
        {% endfor %}
      </select>
    
      <label for='genre'>Choose a Genre:</label>
      <select id='genre' name="genre">
        {% for genre in genres %}
          <option value="{{genre.pk}}">{{genre.name}}</option>
        {% endfor %}
      </select>
    

  </fieldset>
  <input type="submit" value="Add book">
</form>